version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    volumes:
      - ./proto:/app/proto
      - ./server:/app/server

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - GRPC_SERVER_ADDR=server:50051
    volumes:
      - ./proto:/app/proto
      - ./client:/app/client

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: